openapi: 3.0.3
info:
  title: 콘서트 예약 서비스 API
  description: 콘서트 예약 서비스 API 명세서
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: auth
    description: 회원 인증 관련 api
  - name: queue
    description: 콘서트 예약 대기열 api
  - name: concert
    description: 콘서트 관련 api
  - name: reservation
    description: 콘서트 예약 관련 api
  - name: point
    description: 포인트 사용 관련 api
  - name: payment
    description: 결제 관련 api
paths:
  /auth/signup:
    post:
      tags:
        - auth
      summary: 회원가입
      description: 회원 정보를 요청으로 받아 회원을 생성한다
      requestBody:
        description: 회원가입 요청 정보
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: 회원가입 성공 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 400
                message: "잘못된 요청입니다."
        '409':
          description: 중복된 회원 존재
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 409
                message: "이미 존재하는 사용자입니다."
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."

  /auth/signin:
    post:
      tags:
        - auth
      summary: 로그인
      description: 사용자 로그인 요청을 처리하고 응답으로 인증에 필요한 토큰 정보를 반환한다.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninRequest'
      responses:
        '200':
          description: 로그인 성공 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SigninResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 400
                message: "잘못된 요청입니다."
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 401
                message: "아이디 또는 비밀번호가 올바르지 않습니다."
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."

  /concerts:
    get:
      tags:
        - concert
      summary: 콘서트 목록 조회
      description: 관람 가능한 콘서트 목록을 조회한다.
      responses:
        '200':
          description: 콘서트 목록 조회 성공 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcertListResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 400
                message: "잘못된 요청입니다."
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."

  /concerts/{concertId}:
    get:
      tags:
        - concert
      summary: 콘서트 상세 정보 조회
      description: 콘서트 상세 정보를 조회한다.
      parameters:
        - name: concertId
          description: 콘서트 id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: 콘서트 상세 정보 조회 성공 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcertDetailResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 400
                message: "잘못된 요청입니다."
        '404':
          description: 존재하지 않는 콘서트 조회
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 404
                message: "요청하신 콘서트 정보를 찾을 수 없습니다."
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."

  /concerts/{concertId}/schedules:
    get:
      tags:
        - concert
      summary: 예약 가능 날짜 조회
      description: 예약 가능한 콘서트 날짜 목록을 조회한다.
      parameters:
        - name: concertId
          description: 콘서트 id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: 예약 가능 날짜 조회 성공 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationDateResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 400
                message: "잘못된 요청입니다."
        '404':
          description: 존재하지 않는 콘서트 조회
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 404
                message: "요청하신 콘서트 정보를 찾을 수 없습니다."
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."
  /reservation/seats/{scheduleId}:
    get:
      tags:
        - reservation
      summary: 선택한 날짜의 좌석정보 조회
      description: 공연 회차 id로 좌석 정보 목록을 조회한다.
      security:
        - bearerAuth: []
      parameters:
        - name: scheduleId
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: 공연 회차 ID
      responses:
        '200':
          description: 좌석 정보 목록 조회 성공 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationSeatsResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 400
                message: "잘못된 요청입니다."
        '404':
          description: 존재하지 않는 공연 회차
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 404
                message: "존재하지 않는 공연 회차입니다."
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."

  /reservation/seats:
    post:
      tags:
        - reservation
      summary: 좌석 예약 요청
      description: 공연 회차와 좌석 정보를 입력받아 좌석을 예약 처리한다.
      security:
        - bearerAuth: []
      requestBody:
        description: 좌석 예약 요청 정보
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationSeatsInfoRequest'
      responses:
        '200':
          description: 좌석 예약 요청 성공 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationSeatsInfoResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 400
                message: "잘못된 요청입니다."
        '404':
          description: 존재하지 않는 공연 회차 또는 좌석 정보
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                ScheduleNotFound:
                  value:
                    success: false
                    code: 404
                    message: "존재하지 않는 공연 회차입니다."
                SeatNotFound:
                  value:
                    success: false
                    code: 404
                    message: "존재하지 않는 좌석 정보입니다."
                    data:
                      invalidSeatIds: [1]
        '409':
          description: 이용 불가능한 좌석 (예약 완료, 임시 점유 상태인 좌석)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 409
                message: "이용 불가능한 좌석입니다."
                data:
                  unavailableSeatIds: [1]
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."
  /points:
    post:
      tags:
        - point
      summary: 포인트 충전 api
      description: 사용자 식별자 및 충전할 금액을 받아 결제에 사용될 포인트를 충전한다
      security:
        - bearerAuth: []
      requestBody:
        description: 포인트 충전 요청 정보
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PointChargeRequest'
      responses:
        '200':
          description: 포인트 충전 성공 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointChargeResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                GenericBadRequest:
                  value:
                    success: false
                    code: 400
                    message: "잘못된 요청입니다."
                InvalidAmount:
                  value:
                    success: false
                    code: 400
                    message: "충전 금액은 0보다 커야 합니다."
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."
    get:
      tags:
        - point
      summary: 포인트 조회 api
      description: 사용자 식별자를 통해 해당 사용자의 포인트를 조회한다.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 회원 포인트 정보
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 400
                message: "잘못된 요청입니다."
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."

  /payments/{reservationId}:
    get:
      tags:
        - payment
      summary: 결제 정보 조회 api
      description: 결제 전, 결제 정보를 확인한다
      security:
        - bearerAuth: []
      parameters:
        - name: reservationId
          description: 예약 id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: 결제 정보 조회 성공 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentInfoResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 400
                message: "잘못된 요청입니다."
        '404':
          description: 존재하지 않는 예약 id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 401
                message: "존재하지 않는 예약 id 입니다."
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."
  /payments:
    post:
      tags:
        - payment
      summary: 결제 요청 api
      description: 결제 정보를 확인하고 결제를 진행한다
      security:
        - bearerAuth: []
      requestBody:
        description: 결제 요청 정보
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '200':
          description: 결제 요청 성공 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: 클라이언트 에러
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 400
                message: "잘못된 요청입니다."
        '404':
          description: 존재하지 않는 예약 id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 401
                message: "존재하지 않는 예약 id 입니다."
        '409':
          description: 결제 실패 (잔액 부족, 예약 만료 등)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                InsufficientBalance:
                  value:
                    success: false
                    code: 409
                    message: "포인트 잔액이 부족하여 결제에 실패했습니다."
                ReservationExpired:
                  value:
                    success: false
                    code: 409
                    message: "배정된 좌석의 예약 유효 시간이 만료되었습니다."
        '500':
          description: 서버 내부 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                code: 500
                message: "서버 내부 오류가 발생했습니다."

components:
  schemas:
    SignupRequest:
      type: object
      properties:
        id:
          description: 회원가입/로그인 id
          type: string
          example: testId
        password:
          description: 비밀번호
          type: string
          example: testPassword
        username:
          description: 회원 이름
          type: string
          example: testUser
    SignupResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 201
        message:
          description: 응답 메시지
          type: string
          example: "회원이 성공적으로 등록되었습니다."
        data:
          description: 응답 데이터
          type: object
          properties:
            id:
              description: 회원가입/로그인 id
              type: string
              example: testId
            username:
              description: 회원 이름
              type: string
              example: testUser
    SigninRequest:
      type: object
      properties:
        id:
          description: 회원가입/로그인 id
          type: string
          example: testId
        password:
          description: 비밀번호
          type: string
          example: testPassword
    SigninResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 200
        message:
          description: 응답 메시지
          type: string
          example: "회원 로그인에 성공하였습니다."
        data:
          description: 응답 데이터
          type: object
          properties:
            accessToken:
              type: string
            refreshToken:
              type: string
    ConcertListResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 200
        message:
          description: 응답 메시지
          type: string
          example: "콘서트 목록 조회에 성공하였습니다."
        data:
          description: 응답 데이터
          type: object
          properties:
            concerts:
              type: array
              description: 콘서트 목록
              items:
                type: object
                properties:
                  concertId:
                    description: 콘서트 id
                    type: integer
                  title:
                    description: 콘서트명
                    type: string
                  location:
                    description: 콘서트 장소
                    type: string
                  startedAt:
                    description: 콘서트 시작일
                    type: string
                    format: date
                  expiredAt:
                    description: 콘서트 종료일
                    type: string
                    format: date
          example:
            concerts:
              - concertId: 1
                title: "yb 서울 콘서트"
                location: "장충체육관"
                startedAt: "2025-11-13"
                expiredAt: "2025-11-14"
    ConcertDetailResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 200
        message:
          description: 응답 메시지
          type: string
          example: "콘서트 상세 정보 조회에 성공하였습니다."
        data:
          description: 응답 데이터
          type: object
          properties:
            concertId:
              description: 콘서트 id
              type: integer
            title:
              description: 콘서트명
              type: string
            location:
              description: 콘서트 장소
              type: string
            viewingTime:
              description: 콘서트 관람 시간
              type: integer
            startedAt:
              description: 콘서트 시작일
              type: string
              format: date
            expiredAt:
              description: 콘서트 종료일
              type: string
              format: date
            price:
              description: 콘서트 가격
              type: integer
          example:
            concertId: 1
            title: yb 서울 콘서트
            location: 장충체육관
            viewingTime: 2
            startedAt: "2025-11-13"
            expiredAt: "2025-11-14"
            price: 100000
    ReservationDateResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 200
        message:
          description: 응답 메시지
          type: string
          example: "예약 날짜 조회에 성공하였습니다."
        data:
          description: 응답 데이터
          type: object
          properties:
            reservationDates:
              type: array
              description: 예약 가능한 날짜 목록
              items:
                type: object
                properties:
                  scheduleId:
                    description: 공연 회차 id
                    type: integer
                  datetime:
                    description: 예약 가능 날짜 + 시간
                    type: string
                    format: date-time
          example:
            reservationDates:
              - scheduleId: 1
                datetime: "2025-11-13T17:00:00"
              - scheduleId: 2
                datetime: "2025-11-14T18:00:00"
    ReservationSeatsResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 200
        message:
          description: 응답 메시지
          example: "콘서트 좌석 조회에 성공하였습니다."
        data:
          type: object
          description: 응답 데이터
          properties:
            seats:
              type: array
              description: 전체 좌석 목록
              items:
                type: object
                properties:
                  seatId:
                    type: integer
                    description: 좌석 id
                  number:
                    type: string
                    description: 좌석 식별 번호
                  status:
                    type: string
                    description: |
                      좌석 상태 코드
                      - AVAILABLE: 즉시 예약 가능
                      - RESERVED: 예약 완료 (결제 확정)
                      - CANCELED: 예약 취소
                      - HOLD: 예약 보류 (결제 대기 등 임시 점유)
                    enum: [AVAILABLE, RESERVED, CANCELED, HOLD]
                  price:
                    type: integer
                    description: 좌석 가격
          example:
            seats:
              - seatId: 1
                number: A1
                status: AVAILABLE
                price: 100000
              - seatId: 2
                number: A2
                status: HOLD
                price: 100000
              - seatId: 3
                number: A3
                status: RESERVED
                price: 100000
              - seatId: 4
                number: A4
                status: CANCELED
                price: 100000
    ReservationSeatsInfoRequest:
      type: object
      properties:
        scheduleId:
          description: 공연 회차 id
          type: integer
          example: 1
        seatIds:
          type: array
          description: 좌석 id 목록
          items:
            type: integer
          example: [1, 2]
    ReservationSeatsInfoResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 200
        message:
          description: 응답 메시지
          type: string
          example: "콘서트 좌석 예약에 성공하였습니다."
        data:
          description: 응답 데이터
          type: object
          properties:
            reservationId:
              description: 예약 id
              type: integer
              example: 1
    PointChargeRequest:
      type: object
      properties:
        amount:
          description: 충전할 금액
          type: integer
          example: 100000
    PointChargeResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 200
        message:
          description: 응답 메시지
          type: string
          example: "포인트 충전에 성공하였습니다."
    PointResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 200
        message:
          description: 응답 메시지
          type: string
          example: "포인트 조회에 성공하였습니다."
        data:
          description: 응답 데이터
          type: object
          properties:
            point:
              description: 사용자 포인트
              type: integer
              example: 100000
    PaymentInfoResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 200
        message:
          description: 응답 메시지
          type: string
          example: "결제 정보 조회에 성공하였습니다."
        data:
          description: 응답 데이터
          type: object
          properties:
            username:
              description: 회원 이름
              type: string
              example: "testUser"
            title:
              description: 콘서트명
              type: string
              example: "yb 서울 콘서트"
            viewingTime:
              description: 콘서트 관람 시간
              type: integer
              example: 2
            datetime:
              description: 콘서트 날짜 + 시간
              type: string
              format: date-time
              example: "2025-11-13T17:00:00"
            seatNumbers:
              type: array
              description: 좌석 식별 번호 목록
              items:
                type: string
              example: ["A1", "A2"]
            price:
              description: 결제 금액
              type: integer
              example: 100000
    PaymentRequest:
      type: object
      properties:
        reservationId:
          description: 예약 id
          type: integer
          example: 1
        point:
          description: 사용할 포인트 금액
          type: integer
          example: 100000
    PaymentResponse:
      type: object
      properties:
        success:
          description: 요청 성공 여부
          type: boolean
          example: true
        code:
          description: http 상태 코드
          type: integer
          example: 200
        message:
          description: 응답 메시지
          type: string
          example: "결제 요청에 성공하였습니다."
        data:
          description: 응답 데이터
          type: object
          properties:
            paymentId:
              description: |
                결제 식별 id (형식: pt_{uid})
              type: string
              example: "pt_202411130001"
            amount:
              description: 결제 금액
              type: integer
              example: 100000
            status:
              type: string
              description: |
                결제 상태 코드
                - PAID: 결제 완료 및 확정
                - CANCELED: 결제 취소 또는 환불 완료
              enum: [PAID, CANCELED]
              example: PAID
            paidAt:
              description: 결제 승인 일시
              type: string
              format: date-time
              example: "2025-11-01T13:18:21"
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          description: 요청 성공 여부
          example: false
        code:
          type: integer
          description: http 상태 코드
        message:
          type: string
          description: 응답 메시지
        data:
          type: object
          description: 응답 데이터
          nullable: true

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT